#!/usr/bin/env bash

# Set the script to exit if any command fails.
set -euf -o pipefail

# data.json is generated by `python manage.py dumpdata jeetou > data.json`
temp_dir="`mktemp -d`"
temp_file="${temp_dir}/data.json"

# Delete the temp file on exit
trap "rm -rf ${temp_dir}" EXIT

echo "😎  Downloading test data as ${temp_file}"
wget https://www.dropbox.com/s/wa3r50jtfzg5dzj/data.json?dl=1 \
-O "${temp_file}"

echo '😎  Loading data to test DB. It should take less than 1 minute.'
python server/manage.py loaddata "${temp_file}"

echo '😎  Done.'
