# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeetou', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='hashcode',
            field=models.CharField(default='', max_length=32),
        ),
    ]
